/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class Actions {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Actions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Actions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_Actions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Actions() {
    this(jainl16JNI.new_Actions(), true);
  }

  public void clear() {
    jainl16JNI.Actions_clear(swigCPtr, this);
  }

  public void add_move_action(int pcell_id, float position_x, float position_y) {
    jainl16JNI.Actions_add_move_action(swigCPtr, this, pcell_id, position_x, position_y);
  }

  public void add_divide_action(int pcell_id, float position_x, float position_y, float mass) {
    jainl16JNI.Actions_add_divide_action(swigCPtr, this, pcell_id, position_x, position_y, mass);
  }

  public void add_create_virus_action(int pcell_id, float position_x, float position_y) {
    jainl16JNI.Actions_add_create_virus_action(swigCPtr, this, pcell_id, position_x, position_y);
  }

  public void add_surrender_action() {
    jainl16JNI.Actions_add_surrender_action(swigCPtr, this);
  }

}
