/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class GameEndsPlayerVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GameEndsPlayerVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GameEndsPlayerVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_GameEndsPlayerVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GameEndsPlayerVector() {
    this(jainl16JNI.new_GameEndsPlayerVector__SWIG_0(), true);
  }

  public GameEndsPlayerVector(long n) {
    this(jainl16JNI.new_GameEndsPlayerVector__SWIG_1(n), true);
  }

  public long size() {
    return jainl16JNI.GameEndsPlayerVector_size(swigCPtr, this);
  }

  public long capacity() {
    return jainl16JNI.GameEndsPlayerVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    jainl16JNI.GameEndsPlayerVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return jainl16JNI.GameEndsPlayerVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    jainl16JNI.GameEndsPlayerVector_clear(swigCPtr, this);
  }

  public void add(GameEndsPlayer x) {
    jainl16JNI.GameEndsPlayerVector_add(swigCPtr, this, GameEndsPlayer.getCPtr(x), x);
  }

  public GameEndsPlayer get(int i) {
    return new GameEndsPlayer(jainl16JNI.GameEndsPlayerVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, GameEndsPlayer val) {
    jainl16JNI.GameEndsPlayerVector_set(swigCPtr, this, i, GameEndsPlayer.getCPtr(val), val);
  }

}
