/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class PlayerVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PlayerVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PlayerVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_PlayerVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PlayerVector() {
    this(jainl16JNI.new_PlayerVector__SWIG_0(), true);
  }

  public PlayerVector(long n) {
    this(jainl16JNI.new_PlayerVector__SWIG_1(n), true);
  }

  public long size() {
    return jainl16JNI.PlayerVector_size(swigCPtr, this);
  }

  public long capacity() {
    return jainl16JNI.PlayerVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    jainl16JNI.PlayerVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return jainl16JNI.PlayerVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    jainl16JNI.PlayerVector_clear(swigCPtr, this);
  }

  public void add(Player x) {
    jainl16JNI.PlayerVector_add(swigCPtr, this, Player.getCPtr(x), x);
  }

  public Player get(int i) {
    return new Player(jainl16JNI.PlayerVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Player val) {
    jainl16JNI.PlayerVector_set(swigCPtr, this, i, Player.getCPtr(val), val);
  }

}
