/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class PlayerCell {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PlayerCell(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PlayerCell obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_PlayerCell(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPcell_id(int value) {
    jainl16JNI.PlayerCell_pcell_id_set(swigCPtr, this, value);
  }

  public int getPcell_id() {
    return jainl16JNI.PlayerCell_pcell_id_get(swigCPtr, this);
  }

  public void setPlayer_id(int value) {
    jainl16JNI.PlayerCell_player_id_set(swigCPtr, this, value);
  }

  public int getPlayer_id() {
    return jainl16JNI.PlayerCell_player_id_get(swigCPtr, this);
  }

  public void setPosition(Position value) {
    jainl16JNI.PlayerCell_position_set(swigCPtr, this, Position.getCPtr(value), value);
  }

  public Position getPosition() {
    long cPtr = jainl16JNI.PlayerCell_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Position(cPtr, false);
  }

  public void setMass(float value) {
    jainl16JNI.PlayerCell_mass_set(swigCPtr, this, value);
  }

  public float getMass() {
    return jainl16JNI.PlayerCell_mass_get(swigCPtr, this);
  }

  public void setRemaining_isolated_turns(int value) {
    jainl16JNI.PlayerCell_remaining_isolated_turns_set(swigCPtr, this, value);
  }

  public int getRemaining_isolated_turns() {
    return jainl16JNI.PlayerCell_remaining_isolated_turns_get(swigCPtr, this);
  }

  public PlayerCell() {
    this(jainl16JNI.new_PlayerCell(), true);
  }

}
