/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class Player {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Player(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Player obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_Player(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPlayer_id(int value) {
    jainl16JNI.Player_player_id_set(swigCPtr, this, value);
  }

  public int getPlayer_id() {
    return jainl16JNI.Player_player_id_get(swigCPtr, this);
  }

  public void setName(String value) {
    jainl16JNI.Player_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return jainl16JNI.Player_name_get(swigCPtr, this);
  }

  public void setNb_cells(int value) {
    jainl16JNI.Player_nb_cells_set(swigCPtr, this, value);
  }

  public int getNb_cells() {
    return jainl16JNI.Player_nb_cells_get(swigCPtr, this);
  }

  public void setMass(float value) {
    jainl16JNI.Player_mass_set(swigCPtr, this, value);
  }

  public float getMass() {
    return jainl16JNI.Player_mass_get(swigCPtr, this);
  }

  public void setScore(java.math.BigInteger value) {
    jainl16JNI.Player_score_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getScore() {
    return jainl16JNI.Player_score_get(swigCPtr, this);
  }

  public Player() {
    this(jainl16JNI.new_Player(), true);
  }

}
