/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class Position {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Position(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Position obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_Position(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    jainl16JNI.Position_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return jainl16JNI.Position_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    jainl16JNI.Position_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return jainl16JNI.Position_y_get(swigCPtr, this);
  }

  public Position() {
    this(jainl16JNI.new_Position(), true);
  }

}
