/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class Session {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Session(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Session obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_Session(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Session() {
    this(jainl16JNI.new_Session(), true);
  }

  public void connect(String address, int port) throws java.lang.RuntimeException {
    jainl16JNI.Session_connect(swigCPtr, this, address, port);
  }

  public void login_player(String name) throws java.lang.RuntimeException {
    jainl16JNI.Session_login_player(swigCPtr, this, name);
  }

  public void login_visu(String name) throws java.lang.RuntimeException {
    jainl16JNI.Session_login_visu(swigCPtr, this, name);
  }

  public Welcome wait_for_welcome() throws java.lang.RuntimeException {
    return new Welcome(jainl16JNI.Session_wait_for_welcome(swigCPtr, this), true);
  }

  public int wait_for_game_starts() throws java.lang.RuntimeException {
    return jainl16JNI.Session_wait_for_game_starts(swigCPtr, this);
  }

  public void wait_for_next_turn() throws java.lang.RuntimeException {
    jainl16JNI.Session_wait_for_next_turn(swigCPtr, this);
  }

  public void send_actions(Actions actions) throws java.lang.RuntimeException {
    jainl16JNI.Session_send_actions(swigCPtr, this, Actions.getCPtr(actions), actions);
  }

  public Welcome welcome() {
    return new Welcome(jainl16JNI.Session_welcome(swigCPtr, this), true);
  }

  public int current_turn_number() {
    return jainl16JNI.Session_current_turn_number(swigCPtr, this);
  }

  public int player_id() {
    return jainl16JNI.Session_player_id(swigCPtr, this);
  }

  public NeutralCellVector neutral_cells() {
    return new NeutralCellVector(jainl16JNI.Session_neutral_cells(swigCPtr, this), true);
  }

  public PlayerCellVector my_player_cells() {
    return new PlayerCellVector(jainl16JNI.Session_my_player_cells(swigCPtr, this), true);
  }

  public PlayerCellVector ennemy_player_cells() {
    return new PlayerCellVector(jainl16JNI.Session_ennemy_player_cells(swigCPtr, this), true);
  }

  public VirusVector viruses() {
    return new VirusVector(jainl16JNI.Session_viruses(swigCPtr, this), true);
  }

  public boolean is_connected() {
    return jainl16JNI.Session_is_connected(swigCPtr, this);
  }

  public boolean is_logged() {
    return jainl16JNI.Session_is_logged(swigCPtr, this);
  }

  public boolean is_player() {
    return jainl16JNI.Session_is_player(swigCPtr, this);
  }

}
