/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class VirusVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VirusVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirusVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_VirusVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VirusVector() {
    this(jainl16JNI.new_VirusVector__SWIG_0(), true);
  }

  public VirusVector(long n) {
    this(jainl16JNI.new_VirusVector__SWIG_1(n), true);
  }

  public long size() {
    return jainl16JNI.VirusVector_size(swigCPtr, this);
  }

  public long capacity() {
    return jainl16JNI.VirusVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    jainl16JNI.VirusVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return jainl16JNI.VirusVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    jainl16JNI.VirusVector_clear(swigCPtr, this);
  }

  public void add(Virus x) {
    jainl16JNI.VirusVector_add(swigCPtr, this, Virus.getCPtr(x), x);
  }

  public Virus get(int i) {
    return new Virus(jainl16JNI.VirusVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Virus val) {
    jainl16JNI.VirusVector_set(swigCPtr, this, i, Virus.getCPtr(val), val);
  }

}
