/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class Welcome {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Welcome(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Welcome obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_Welcome(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParameters(GameParameters value) {
    jainl16JNI.Welcome_parameters_set(swigCPtr, this, GameParameters.getCPtr(value), value);
  }

  public GameParameters getParameters() {
    long cPtr = jainl16JNI.Welcome_parameters_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GameParameters(cPtr, false);
  }

  public void setInitial_ncells_positions(PositionVector value) {
    jainl16JNI.Welcome_initial_ncells_positions_set(swigCPtr, this, PositionVector.getCPtr(value), value);
  }

  public PositionVector getInitial_ncells_positions() {
    long cPtr = jainl16JNI.Welcome_initial_ncells_positions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PositionVector(cPtr, false);
  }

  public Welcome() {
    this(jainl16JNI.new_Welcome(), true);
  }

}
