/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class NeutralCell {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NeutralCell(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NeutralCell obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_NeutralCell(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    jainl16JNI.NeutralCell_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return jainl16JNI.NeutralCell_id_get(swigCPtr, this);
  }

  public void setPosition(Position value) {
    jainl16JNI.NeutralCell_position_set(swigCPtr, this, Position.getCPtr(value), value);
  }

  public Position getPosition() {
    long cPtr = jainl16JNI.NeutralCell_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Position(cPtr, false);
  }

  public void setMass(float value) {
    jainl16JNI.NeutralCell_mass_set(swigCPtr, this, value);
  }

  public float getMass() {
    return jainl16JNI.NeutralCell_mass_get(swigCPtr, this);
  }

  public void setIs_initial(boolean value) {
    jainl16JNI.NeutralCell_is_initial_set(swigCPtr, this, value);
  }

  public boolean getIs_initial() {
    return jainl16JNI.NeutralCell_is_initial_get(swigCPtr, this);
  }

  public void setRemaining_turns_before_apparition(int value) {
    jainl16JNI.NeutralCell_remaining_turns_before_apparition_set(swigCPtr, this, value);
  }

  public int getRemaining_turns_before_apparition() {
    return jainl16JNI.NeutralCell_remaining_turns_before_apparition_get(swigCPtr, this);
  }

  public void setIs_alive(boolean value) {
    jainl16JNI.NeutralCell_is_alive_set(swigCPtr, this, value);
  }

  public boolean getIs_alive() {
    return jainl16JNI.NeutralCell_is_alive_get(swigCPtr, this);
  }

  public NeutralCell() {
    this(jainl16JNI.new_NeutralCell(), true);
  }

}
