/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class PlayerCellVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PlayerCellVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PlayerCellVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_PlayerCellVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PlayerCellVector() {
    this(jainl16JNI.new_PlayerCellVector__SWIG_0(), true);
  }

  public PlayerCellVector(long n) {
    this(jainl16JNI.new_PlayerCellVector__SWIG_1(n), true);
  }

  public long size() {
    return jainl16JNI.PlayerCellVector_size(swigCPtr, this);
  }

  public long capacity() {
    return jainl16JNI.PlayerCellVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    jainl16JNI.PlayerCellVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return jainl16JNI.PlayerCellVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    jainl16JNI.PlayerCellVector_clear(swigCPtr, this);
  }

  public void add(PlayerCell x) {
    jainl16JNI.PlayerCellVector_add(swigCPtr, this, PlayerCell.getCPtr(x), x);
  }

  public PlayerCell get(int i) {
    return new PlayerCell(jainl16JNI.PlayerCellVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, PlayerCell val) {
    jainl16JNI.PlayerCellVector_set(swigCPtr, this, i, PlayerCell.getCPtr(val), val);
  }

}
