/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.contest16;

public class PositionVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PositionVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PositionVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jainl16JNI.delete_PositionVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PositionVector() {
    this(jainl16JNI.new_PositionVector__SWIG_0(), true);
  }

  public PositionVector(long n) {
    this(jainl16JNI.new_PositionVector__SWIG_1(n), true);
  }

  public long size() {
    return jainl16JNI.PositionVector_size(swigCPtr, this);
  }

  public long capacity() {
    return jainl16JNI.PositionVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    jainl16JNI.PositionVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return jainl16JNI.PositionVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    jainl16JNI.PositionVector_clear(swigCPtr, this);
  }

  public void add(Position x) {
    jainl16JNI.PositionVector_add(swigCPtr, this, Position.getCPtr(x), x);
  }

  public Position get(int i) {
    return new Position(jainl16JNI.PositionVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Position val) {
    jainl16JNI.PositionVector_set(swigCPtr, this, i, Position.getCPtr(val), val);
  }

}
